### PR TITLE
Add video controls

### PR DESCRIPTION
**Pull request by Allicolyer**
Hey @georgemandis or @samson212, would either of you be willing to test this with me later or on Monday? I tested it locally and I think it works.

### CODE REVIEW

**Comment by georgemandis** [comment]
I just tested it locally and it looks like it works to me! Nice work :)

Maybe we could add some kind of visual cue that lets people know when "mute" is activated though? On both sides of the conversation, kind of like how Zoom does?

Indicating to the user they've muted themselves should be pretty straightforward. Indicating to the other person that they've been muted might require sending some additional "data" to them over the peer connection, though I'm not entirely sure.

**Comment by Allicolyer** [comment]
👍 Okay, I got some toggling text going on the buttons. I think I have an idea of how to send the "data" over to the other person.

**Comment by georgemandis** [comment]
Cool! I think the way it works is something like this:

- We'd have to add a listener for a general `connection` event on our peer object (` peer.on("connection"`). Right now we're just listening for `call` events. 
- This should give us an object (`conn`) that contains the other Peer's ID and methods we can use to listen to events specific to that peer— `conn.on("data")`
- This should also give us the ability to send data to that peer directly — `conn.send(dataJSONObject)`

I might be remembering that wrong, but i *think* that's the gist of how sending arbitrary works with PeerJS. Documentation under **Usage > Data connections** should outline more thoroughly: [https://peerjs.com/docs.html#api](https://peerjs.com/docs.html#api)

**Comment by Allicolyer** [comment]
Hey thanks @georgemandis! This makes sense. I'll give it a try later.

**Comment by Allicolyer** [comment]
Okay I'm getting a little stuck here: 

```
//make connection to peer
peer.on("connection", function(conn) {
  conn.on("data", function(data) {
    console.log("I've attempted to recieve a message???");
    // console.log("Received", data);
  });

  conn.on("open", function() {
    // Send messages
    console.log("I've sent a hello greeting");
    conn.send("Hello!");
  });
});
```

The `conn.on("data", function(data){...}` doesn't seem to be firing. 

I'm also getting `ERROR PeerServer:  Message unrecognized` in the node console

**Comment by Allicolyer** [comment]
hey @georgemandis! hahaha, it looks like I did the exact thing this sassy article advises not to do. I was doing it for styling reasons. Thanks for this! I'm going to roll this back 😄

**Pull request merged**
