### PR TITLE
Moved app logic into its own file

### PR DESCRIPTION
**Pull request by georgemandis**
I think it's time to decouple the JavaScript from the main file.

I'll leave it to you, @Allicolyer or @samson212, to merge.

### CODE REVIEW

**Comment by Allicolyer** [comment]
hmmm I'll need to take a careful look. What do you think @samson212?

**Comment by georgemandis** [comment]
Please review and comment on every single line. It's the only way I will know your reviews are thorough.

**Comment by Allicolyer** [comment]
Okay, I'm pulling it down locally, I think I can get to this in the next few weeks or so.

**Comment by georgemandis** [comment]
Whoa, weeks? Sounds too fast. Hope you're not cutting any corners.

**Comment by Allicolyer** [comment]
I'm making moves!!!!!!!!

**Pull request merged**
