### PR TITLE
Save previous matches

### PR DESCRIPTION
**Pull request by Allicolyer**
Hey @georgemandis or @samson212 tell me what you think! This remembers everyone who you matched with for 1 week.

### CODE REVIEW

**Review by georgemandis — COMMENTED** [review]
I think is great and does just what we need for now. I wonder how it will look though if you have a 10+ people in your matched list? Does the comma-separated, horizontal layout still make the most sense? Or should we move things into an ordinal list?

Things to ponder, but I think it's good!

**Comment by Allicolyer** [comment]
I was sort of worried the page would get too long ... what do you think?
localhost_9000_

localhost_9000_ (1)

**Comment by georgemandis** [comment]
It might be a little hacky but we could use CSS columns??
https://developer.mozilla.org/en-US/docs/Web/CSS/columns

**Comment by Allicolyer** [comment]
oh cool! I've never played with CSS columns. Could we also do this with flexbox? Give each span like 20% width and have them wrap around?  I guess those might get misaligned but the columns won't?

**Comment by Allicolyer** [comment]
Actually I think this might work!
localhost_9000_

**Comment by georgemandis** [comment]
Yeah, that's kind what I was thinking! Might work well enough for now.  

I'm not sure but I think the "order" gets a little confused, though that may not matter. I think it will try to fill the 3 columns right away, so the first 3 matches will each have their own column. When the 4th gets added it might be columns of 2, 1 and 1... Maybe it doesn't work that way, but I have a vague memory of it being a little funky like that?

**Pull request merged**
